"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const multer_1 = __importDefault(require("multer"));
const upload_1 = __importDefault(require("./config/upload"));
const SalaController_1 = require("./controllers/SalaController");
const salaController = new SalaController_1.SalaController();
const router = (0, express_1.Router)();
exports.router = router;
const upload = (0, multer_1.default)(upload_1.default);
router.get("/salas/pagina/:pag", salaController.showAll);
router.get("/salas/totalpaginas", salaController.countPags);
router.get("/salas/:id", salaController.show);
router.post("/salas/salvar", upload.array('images'), salaController.create);
router.put("/salas/atualizar", upload.array('images'), salaController.update);
router.delete("/salas/deletar/:id", salaController.delete);
